# Generated by Django 4.1.4 on 2023-08-29 09:29

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_desc', tinymce.models.HTMLField()),
                ('product_price', models.IntegerField(default=None)),
                ('product_image', models.ImageField(default=None, max_length=250, null=True, upload_to='products/')),
            ],
        ),
    ]
