# Generated by Django 4.1.4 on 2023-09-08 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productcart', '0004_products_discounted_price_products_showcase_badge_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='product_image',
            new_name='product_image1',
        ),
        migrations.AddField(
            model_name='products',
            name='product_image2',
            field=models.ImageField(default=None, max_length=250, null=True, upload_to='products/'),
        ),
    ]
