# Generated by Django 4.1.4 on 2023-09-08 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productcart', '0005_rename_product_image_products_product_image1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='product_image1',
            new_name='product_image',
        ),
        migrations.RemoveField(
            model_name='products',
            name='product_image2',
        ),
    ]
