# Generated by Django 4.1.4 on 2023-09-08 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productcart', '0006_rename_product_image1_products_product_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
